version: '3'

services:
  mongodb:
    image: mongo:latest
    logging:
      driver: none
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongodb:27017/internsathi
      - JWT_EXPIRES_IN=30m
      - JWT_SECRET=SuperDifficultSecretKey
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
